### ISSUE TITLE
Error installing dbxcli

### ISSUE THREAD

**Issue by simoalx** [idleberg/homebrew-asahi#1]
```
┌─[ ~ ]
➜ brew install dbxcli
==> Downloading https://ghcr.io/v2/homebrew/core/dbxcli/manifests/64
curl: (22) The requested URL returned error: 404

==> Fetching idleberg/asahi/dbxcli
==> Downloading https://ghcr.io/v2/homebrew/core/dbxcli/blobs/sha256:558728b5567
curl: (22) The requested URL returned error: 404

Error: dbxcli: Failed to download resource "dbxcli"
Download failed: https://ghcr.io/v2/homebrew/core/dbxcli/blobs/sha256:558728b5567bd1dc68e9612a51df346c56019de2f69df592150e77e46a979061
```

**Comment by idleberg** [comment]
Thanks, I've noticed this myself and wondered about it. I'm not sure how `ghcr.io` is involved in all this. I'm pretty sure one could download the pre-built client from the old tap. Build from source works just fine.

My first instinct was that my tap might not have been indexed yet by Homebrew, so I'd give it a few days. In the meantime, I updated the `README.md` to advocate the use of `--build-from-source`.
